# This is a basic workflow to help you get started with Actions

name: Called

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
runs:
  using: "composite"
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo ${{ inputs.name }} >> name.txt

